### PR TITLE
enable download models from url in merged_models.json

### PR DESCRIPTION
**Pull request by Chafid**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Hi @willwade , please check this PR for downloading new models using merged_models.json

### CODE REVIEW

**Comment by willwade** [comment]
Question
- 1. DO you think we should create a dev function. It would a) get huggingface JSON b) generate JSON using createindex.py - c) merge both JSON and save to the repo. Remove any other json in this repo
- 2. sherpa-onnx then would getVoices with no token or model path - with ALL data in the local JSON. Actually speeding things up as the end user doesnt download this file..
- 3. rename local download path to not ~/mms but ~/sherpaonnx or something more relevant

I think a user should be able to provide their own onnx path - and then settings for this generation too.. 

I have a feeling it may not work great. In part because my createindex.py was broken. It was calculating the language codes correctly of each model etc.

**Comment by willwade** [comment]
You'll hate this.. i do to but its worth it!

install ruff
pip install ruff
then 

ruff check --select=ALL --fix --unsafe-fixes  tts_wrapper/engines/sherpaonnx/client.py

run through it and see if you can fix it - ignore line length issues. 

I'll do this on ALL the code at some stage but for now we might as well start with this engine which is definitely one of the most complex

**Comment by Chafid** [comment]
Ok Will, I'll check this out

**Comment by Chafid** [comment]
Hi @willwade , updated with changes from ruff. 
I'll create a new PR for the auto generation of model list json

**Comment by willwade** [comment]
Great. Let me merge this so we don't lose track of things too much. I'm still fiddling with the other big pr on formatting & tests (I merged it into it). I'll try and get that as far as I can today and merge that too.

**Pull request merged**
