### PR TITLE
Add unit test for all engines

### PR DESCRIPTION
**Pull request by Chafid**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by willwade — COMMENTED** [review]
I know its a total pain.. But can we try and use the same logic as in tests/test_tts_engines.py where env vars are plainly used

Maybe answer is to keep that nice load_credentials code actually but define the keys - and then search env vars IF No credentials json there

NB: One bonus is we can now use a google creds json as a dictionary so that too can be in env vars. BUT you have to do a hideous thing like convert the original file to a base64 then decode it - see https://github.com/AceCentre/AACSpeakHelper/blob/f028197b3249166d3e4258b3f7779f31c704c141/configure_enc_utils.py#L18

**Comment by willwade** [comment]
NB: SAPI Is broken right now.. https://github.com/willwade/tts-wrapper/issues/24 so this will fail

**Comment by Chafid** [comment]
Got it Will, I'll update it like in the  tests/test_tts_engines.py

**Comment by willwade** [comment]
Just holding back until we can fully check things as this Im pretty sure will break the CI stuff.. Will do this later. Thanks @Chafid

**Comment by willwade** [comment]
@Chafid im going to merge this unless you can see a reason not to

**Comment by willwade** [comment]
Im going to close this - its now all in #37

**Pull request closed without merging**
