### PR TITLE
Implement pause resume functionality

### PR DESCRIPTION
**Pull request by Chafid**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Add example file for google on how to use the pause resume functionality

### CODE REVIEW

**Comment by willwade** [comment]
Ok My idea..

dont do import pyaudio like that  use lazy loading. but maybe with a statement like 'usePyAudio' or 'usePlayResume' or something? so we may need that flag on the init of tts client ??

**Comment by Chafid** [comment]
hi @willwade , how about this?

`    def load_audio(self, audio_bytes):
        import pyaudio
        """Load audio bytes into the player"""
        self.pyaudio = pyaudio.PyAudio()
        if not audio_bytes:
            raise ValueError("Audio bytes cannot be empty")        
        self.audio_bytes = audio_bytes
        self.position = 0`
        
 since load_audio is only used for pause and resume, we can load the pyaudio library when this is called

**Comment by willwade** [comment]
Yeah. That makes sense

**Comment by willwade** [comment]
Great - can you update the docs how we would use this - i think mainly in the setup of this with the optional

**Pull request merged**
